### ISSUE TITLE
cannot later associate a tag with an app

### ISSUE THREAD

**Issue by tomhenderson** [abhijithanilkumar/ns-3-AppStore#17]
I tried to edit the WOSS app and associate it with the newly created 'Underwater Acoustic Networks' tag, but I couldn't get it to stick.

**Comment by tomhenderson** [comment]
![uan-tags](https://user-images.githubusercontent.com/402771/29366214-4662afa2-824e-11e7-8608-d322583dfb20.png)

**Comment by abhijithanilkumar** [comment]
The tag is associated. This is an issue with the search index building. I'll setup a hook that runs the command whenever the DB is changed.
