### ISSUE TITLE
avoid pluralizing instructions and maintenance; rename 'instructions' to 'installation'

### ISSUE THREAD

**Issue by tomhenderson** [abhijithanilkumar/ns-3-AppStore#21]
The pluralization of 'instructions' and 'maintenance' on this page may be interpreted as a misspelling.  I suggest to leave it as 'Instructions' and 'Maintenance'

**Comment by tomhenderson** [comment]
![instructionss](https://user-images.githubusercontent.com/402771/29367127-c4b0df62-8250-11e7-9287-6708a63d73aa.png)

**Comment by tomhenderson** [comment]
Also, 'Instructions' should be 'Installation'

**Comment by abhijithanilkumar** [comment]
This is another effect of the default Django admin panel. I found a way to override the names, I'll use it to change the same.
