### ISSUE TITLE
Support markdown or html in release notes

### ISSUE THREAD

**Issue by tomhenderson** [abhijithanilkumar/ns-3-AppStore#23]
How can we support bullet lists or other formatting such as the release notes for v1.5.0 found on this page?

http://telecom.dei.unipd.it/ns/woss/doxygen/Changelog.html

**Comment by abhijithanilkumar** [comment]
It supports markdown right now. I have modified it as you can see at http://ns-apps.ee.washington.edu/app/worldoceansimulationsystem/ .
You can create new bullet points using '*'. The site supports markdown similar to GitHub markdown.
