### ISSUE TITLE
how to handle dev version

### ISSUE THREAD

**Issue by tomhenderson** [abhijithanilkumar/ns-3-AppStore#24]
It seems that it may be awkward to treat the development version of a module exactly the same as a release.  My goal is that the app store will serve the XML of the development repo for users interested in it, but perhaps there needs to be an attribute in the XML or else in the app metadata to distinguish a release from a development tree.

Development version should not show up on the Releases tab.

**Comment by tomhenderson** [comment]
![dev](https://user-images.githubusercontent.com/402771/29369402-5e745916-8257-11e7-9d25-8660c13afb3a.png)

**Comment by abhijithanilkumar** [comment]
Where do you want the development version to be ?
