### ISSUE TITLE
search bar is limited

### ISSUE THREAD

**Issue by tomhenderson** [abhijithanilkumar/ns-3-AppStore#28]
On the top search bar, I was able to search for 'Epidemic', but searches for 'Underwater', or 'World', turned up nothing.  What metadata is searched by this bar?

**Comment by tomhenderson** [comment]
After I went into World Ocean Simulation System and enabled the 'Underwater Acoustic network' tag, it started to be searchable.  Is this field only searching on tags?

**Comment by abhijithanilkumar** [comment]
It's searchable on everything. But the search works on Apps that have `active=True`.
