### ISSUE TITLE
ordering of ns-releases

### ISSUE THREAD

**Issue by tomhenderson** [abhijithanilkumar/ns-3-AppStore#32]
I added a couple of past releases (3.22 and then 3.26) and now the pull-down menu shows '3.27' followed by '3.22' followed by '3.26'; can these be reordered?  Can the default be to insert a new ns-3 release at the top of the menu bar?

Similarly, I have a question about how we organize tags as the tag list grows; we may want to reorder.

**Comment by abhijithanilkumar** [comment]
I'll order ns-3 versions according to name. For tags, we can use count, ie, the number of apps with the given tag.
